//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i18n {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FritzHome.Resources.de", typeof(de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stunden ähnelt.
        /// </summary>
        internal static string Chart_Day {
            get {
                return ResourceManager.GetString("Chart_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minuten ähnelt.
        /// </summary>
        internal static string Chart_Hour {
            get {
                return ResourceManager.GetString("Chart_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tage ähnelt.
        /// </summary>
        internal static string Chart_Month {
            get {
                return ResourceManager.GetString("Chart_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature °C ähnelt.
        /// </summary>
        internal static string Chart_Temperature {
            get {
                return ResourceManager.GetString("Chart_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volt ähnelt.
        /// </summary>
        internal static string Chart_V {
            get {
                return ResourceManager.GetString("Chart_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watt ähnelt.
        /// </summary>
        internal static string Chart_W {
            get {
                return ResourceManager.GetString("Chart_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tage ähnelt.
        /// </summary>
        internal static string Chart_Week {
            get {
                return ResourceManager.GetString("Chart_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energieverbrauch (Wh) ähnelt.
        /// </summary>
        internal static string Chart_Wh {
            get {
                return ResourceManager.GetString("Chart_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monate ähnelt.
        /// </summary>
        internal static string Chart_Year {
            get {
                return ResourceManager.GetString("Chart_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annex ähnelt.
        /// </summary>
        internal static string Detail_Annex {
            get {
                return ResourceManager.GetString("Detail_Annex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batterie ähnelt.
        /// </summary>
        internal static string Detail_Battery {
            get {
                return ResourceManager.GetString("Detail_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ähnelt.
        /// </summary>
        internal static string Detail_Color {
            get {
                return ResourceManager.GetString("Detail_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energieverbrauch (Wh) ähnelt.
        /// </summary>
        internal static string Detail_Energie {
            get {
                return ResourceManager.GetString("Detail_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firmware ähnelt.
        /// </summary>
        internal static string Detail_Firmware {
            get {
                return ResourceManager.GetString("Detail_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FritzBox ähnelt.
        /// </summary>
        internal static string Detail_Fritzbox {
            get {
                return ResourceManager.GetString("Detail_Fritzbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identifier ähnelt.
        /// </summary>
        internal static string Detail_Indentifier {
            get {
                return ResourceManager.GetString("Detail_Indentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimmer (%) ähnelt.
        /// </summary>
        internal static string Detail_Level {
            get {
                return ResourceManager.GetString("Detail_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OEM ähnelt.
        /// </summary>
        internal static string Detail_Manufacturer {
            get {
                return ResourceManager.GetString("Detail_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modell ähnelt.
        /// </summary>
        internal static string Detail_Model {
            get {
                return ResourceManager.GetString("Detail_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Detail_Name {
            get {
                return ResourceManager.GetString("Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revision ähnelt.
        /// </summary>
        internal static string Detail_Revision {
            get {
                return ResourceManager.GetString("Detail_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SerienNr. ähnelt.
        /// </summary>
        internal static string Detail_Serial {
            get {
                return ResourceManager.GetString("Detail_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus ähnelt.
        /// </summary>
        internal static string Detail_SwitchOff {
            get {
                return ResourceManager.GetString("Detail_SwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An ähnelt.
        /// </summary>
        internal static string Detail_SwitchOn {
            get {
                return ResourceManager.GetString("Detail_SwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Themperatur (°C) ähnelt.
        /// </summary>
        internal static string Detail_Themprature {
            get {
                return ResourceManager.GetString("Detail_Themprature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Komfort Themperatur (°C) ähnelt.
        /// </summary>
        internal static string Detail_ThempratureConfort {
            get {
                return ResourceManager.GetString("Detail_ThempratureConfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absenk Themperatur (°C) ähnelt.
        /// </summary>
        internal static string Detail_ThempratureLow {
            get {
                return ResourceManager.GetString("Detail_ThempratureLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll Themperatur (°C) ähnelt.
        /// </summary>
        internal static string Detail_ThempratureTarget {
            get {
                return ResourceManager.GetString("Detail_ThempratureTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schalter ähnelt.
        /// </summary>
        internal static string Device_Button {
            get {
                return ResourceManager.GetString("Device_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leuchtmittel ähnelt.
        /// </summary>
        internal static string Device_Lightbulb {
            get {
                return ResourceManager.GetString("Device_Lightbulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewegungsmelder ähnelt.
        /// </summary>
        internal static string Device_Motion {
            get {
                return ResourceManager.GetString("Device_Motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolladensteuerung ähnelt.
        /// </summary>
        internal static string Device_Shutter {
            get {
                return ResourceManager.GetString("Device_Shutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rauchmelder ähnelt.
        /// </summary>
        internal static string Device_Smoke {
            get {
                return ResourceManager.GetString("Device_Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steckdose ähnelt.
        /// </summary>
        internal static string Device_Socket {
            get {
                return ResourceManager.GetString("Device_Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thermostat ähnelt.
        /// </summary>
        internal static string Device_Thermostat {
            get {
                return ResourceManager.GetString("Device_Thermostat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarmmelder ähnelt.
        /// </summary>
        internal static string Function_Alarm {
            get {
                return ResourceManager.GetString("Function_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ähnelt.
        /// </summary>
        internal static string Function_Color {
            get {
                return ResourceManager.GetString("Function_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energiemeter ähnelt.
        /// </summary>
        internal static string Function_Energiemeter {
            get {
                return ResourceManager.GetString("Function_Energiemeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimmer ähnelt.
        /// </summary>
        internal static string Function_Level {
            get {
                return ResourceManager.GetString("Function_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schalter ähnelt.
        /// </summary>
        internal static string Function_Switch {
            get {
                return ResourceManager.GetString("Function_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thermometer ähnelt.
        /// </summary>
        internal static string Function_Thermometer {
            get {
                return ResourceManager.GetString("Function_Thermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string License_Close {
            get {
                return ResourceManager.GetString("License_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spenden ähnelt.
        /// </summary>
        internal static string License_Donate {
            get {
                return ResourceManager.GetString("License_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gültig bis ähnelt.
        /// </summary>
        internal static string License_Expires {
            get {
                return ResourceManager.GetString("License_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzschlüssel ähnelt.
        /// </summary>
        internal static string License_Key {
            get {
                return ResourceManager.GetString("License_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        internal static string License_Reload {
            get {
                return ResourceManager.GetString("License_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenz Informationen ähnelt.
        /// </summary>
        internal static string License_Titel {
            get {
                return ResourceManager.GetString("License_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenztyp ähnelt.
        /// </summary>
        internal static string License_Type {
            get {
                return ResourceManager.GetString("License_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build ähnelt.
        /// </summary>
        internal static string License_Version {
            get {
                return ResourceManager.GetString("License_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string Menu_DE {
            get {
                return ResourceManager.GetString("Menu_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        internal static string Menu_EN {
            get {
                return ResourceManager.GetString("Menu_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FritzBox ähnelt.
        /// </summary>
        internal static string Menu_Fritzbox {
            get {
                return ResourceManager.GetString("Menu_Fritzbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenz Informationen ähnelt.
        /// </summary>
        internal static string Menu_License {
            get {
                return ResourceManager.GetString("Menu_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string Menu_Quit {
            get {
                return ResourceManager.GetString("Menu_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version Aktualisieren ähnelt.
        /// </summary>
        internal static string Menu_Update {
            get {
                return ResourceManager.GetString("Menu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung ähnelt.
        /// </summary>
        internal static string Settings_Conenction {
            get {
                return ResourceManager.GetString("Settings_Conenction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FritzBox ähnelt.
        /// </summary>
        internal static string Settings_Group {
            get {
                return ResourceManager.GetString("Settings_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string Settings_Ok {
            get {
                return ResourceManager.GetString("Settings_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennwort ähnelt.
        /// </summary>
        internal static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string Settings_Titel {
            get {
                return ResourceManager.GetString("Settings_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fritzbox / Uri ähnelt.
        /// </summary>
        internal static string Settings_Uri {
            get {
                return ResourceManager.GetString("Settings_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutername ähnelt.
        /// </summary>
        internal static string Settings_Username {
            get {
                return ResourceManager.GetString("Settings_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überprüfen ähnelt.
        /// </summary>
        internal static string Settings_Validate {
            get {
                return ResourceManager.GetString("Settings_Validate", resourceCulture);
            }
        }
    }
}
